version: "3.8"
services:
  microapp:
    image: "juxsta/pcmicroapp"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "8080:8080"
    entrypoint: "yarn"
    command: "run serve"