version: "3.8"
services:
  microapp:
    image: "juxsta/pcmicroapp"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/usr/src/app
    ports:
      - "8080:8080"
    entrypoint: yarn
    command: "run serve"